/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'brand-primary': '#2563EB',
        'primary-hover': '#1D4ED8',
        'primary-active': '#1E40AF',
        'primary-light': '#DBEAFE',
        'primary-extra-light': '#EFF6FF',
        'page-background': '#F8FAFC',
        'card-background': '#FFFFFF',
        'secondary-background': '#F1F5F9',
        'hover-background': '#F1F5F9',
        'active-background': '#E2E8F0',
        'primary-text': '#0F172A',
        'secondary-text': '#475569',
        'tertiary-text': '#64748B',
        'disabled-text': '#94A3B8',
        'critical-background': '#FEE2E2',
        'critical-border': '#FCA5A5',
        'critical-text': '#991B1B',
        'critical-accent': '#DC2626',
        'medium-background': '#FEF3C7',
        'medium-border': '#FCD34D',
        'medium-text': '#92400E',
        'medium-accent': '#F59E0B',
        'low-background': '#D1FAE5',
        'low-border': '#6EE7B7',
        'low-text': '#065F46',
        'low-accent': '#10B981',
        'chart-1': '#3B82F6',
        'chart-2': '#8B5CF6',
        'chart-3': '#EC4899',
        'chart-4': '#10B981',
        'chart-5': '#F59E0B',
        'chart-6': '#06B6D4',
        'default-border': '#E2E8F0',
        'focus-border': '#2563EB',
        divider: '#CBD5E1',
      },
      fontFamily: {
        sans: [
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'Roboto',
          'Oxygen',
          'Ubuntu',
          'Cantarell',
          'Fira Sans',
          'Droid Sans',
          'Helvetica Neue',
          'sans-serif',
        ],
      },
      boxShadow: {
        card: '0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)',
        'card-hover':
          '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
        large:
          '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
      },
    },
  },
  plugins: [],
};
